# render.yaml

services:
  - type: web
    name: onlinebookstore-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter      # free tier
    buildCommand: ""   # Dockerfile handles building everything
    startCommand: ""   # ENTRYPOINT + CMD in Dockerfile start MySQL & Apache
